title: "Maksuda Aktar Toma"
email: mtoma2@huskers.unl.edu
url: "https://maksudatoma.github.io"
author: "Maksuda Aktar Toma"
github_username: maksudatoma
theme: minima
avatar: "/git.jpeg"

header_pages:
  - index.md
  - projects.md
  - publications.md
  - presentations.md
  - award.md
  - teaching.md